[package]
name = "rs-ucan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
did-key = "0.1.0"
anyhow = "1.0.52"
serde_json = "1.0.74"
serde = "1.0.133"
base64 = "0.13.0"
textnonce = "1.0.0"
log = "0.4.14"