[package]
name = "ucan"
description = "Implement UCAN-based authorization with conciseness and ease!"
keywords = ["ucan", "authz", "jwt", "pki"]
categories = [
  "authorization",
  "cryptography",
  "encoding",
  "web-programming"
]
documentation = "https://docs.rs/ucan"
repository = "https://github.com/cdata/rs-ucan/"
homepage = "https://github.com/cdata/rs-ucan"
license = "Apache-2.0"
readme = "README.md"
version = "0.6.0-alpha.1"
edition = "2021"

[features]
default = []
web = ["instant/wasm-bindgen"]

[dependencies]
anyhow = "^1"
async-trait = "0.1"
async-recursion = "^1"
async-std = "^1"
serde_json = "^1"
serde = { version = "^1", features = ["derive"] }
base64 = "0.13"
textnonce = "^1"
log = "0.4"
url = "^2"
bs58 = "0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
instant = { version = "0.1" }

[dev-dependencies]
did-key = "0.1"
tokio = { version = "^1", features = ["macros", "rt"] }