on: push

name: Run test suite

jobs:
  run-test-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            ./target
          key: ${{ runner.os }}-cargo-artifacts
      - run: cargo test
        shell: bash
  publish-release:
    runs-on: ubuntu-latest
    needs: [run-test-suite]
    if: ${{ github.event.ref == 'refs/heads/main' && endsWith(github.event.head_commit.message, '!release_candidate') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            ./target
          key: ${{ runner.os }}-cargo-publish-artifacts
      - run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          cargo publish
        shell: bash
